### ISSUE TITLE
Scrolling Issue...

### ISSUE THREAD

**Issue by ambujshukla** [mokagio/UICollectionViewLeftAlignedLayout#10]
Hello...I have used this by downloading the files and set Class to UICollectionViewLeftAlignedLayout but at first time it gets stuck while scrolling and then scrolls properly...So please help me with this issue...

**Comment by ambujshukla** [comment]
It was my issue and it been solved.

**Comment by mokagio** [comment]
I'm glad you were able to solve your issue 😊 Sorry I couldn't answer sooner...
