### ISSUE TITLE
I am having trouble making each cell have a different size

### ISSUE THREAD

**Issue by webmagnets** [mokagio/UICollectionViewLeftAlignedLayout#2]
Do you have time to help me get that going?

Maybe a google hangouts or something.

**Comment by mokagio** [comment]
Hi @webmagnets I don't have time for an hangout sorry, but I'm happy to answer you questions here, or via email if you prefer. I'll try to be as quick as I can.

Here something that might help, if you look at the [example code](https://github.com/mokagio/UICollectionViewLeftAlignedLayout/blob/master/Example/Example/ExampleViewController.m) you'll see that the way we set the cells to different sizes is by implementing the `- collectionView:layout:sizeForItemAtIndexPath:` method of `UICollectionViewDelegate`.

```objc
- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath
{
    CGFloat randomWidth = (arc4random() % 120) + 60;
    return CGSizeMake(randomWidth, 60);
}
```

**Comment by webmagnets** [comment]
That works perfectly. However, I am having trouble getting the width of the subview of the cell. I want the cell to always be just 5 points or so bigger than the label it contains.

I have tried this...

```Swift
func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
    let wordCell = collectionView.cellForItemAtIndexPath(indexPath) as ReadArticleCollectionViewCell // ERROR on this line
    println("the word label width is \(wordCell.wordLabel.frame.size.width)")
    return CGSizeMake(wordCell.wordLabel.frame.size.width, 50)
}
```

... but I keep getting an error that says ```fatal error: unexpectedly found nil while unwrapping an Optional value.``` I don't see why it would be nil. Aren't all the cells non-nil?

**Comment by mokagio** [comment]
I see... The reason you get `nil` cells is because the cells are actually `nil`. In fact `collectionView(_:layout:sizeForItemAtIndexPath:)` is called **before** `collectionView(_:cellForRowAtIndexPath:)`, put two breakpoints to have a confirmation.

If I guess what you're trying to do is to have cells that contain a label and that are sized base on it. Is it correct?

**Comment by webmagnets** [comment]
That is correct.




-
Nathan Cain
501-463-6336www.jw.org

------------------

[+] Add me to your address book

**Comment by mokagio** [comment]
Ok, the best solution to have _dynamic sizing_ cells is to use Auto Layout. Unfortunately there is not a lot of documentation on how to do such thing nicely with `UICollectionView`. On the other hand there's plenty of documentation on how to do it with `UITableView` and adapting it shouldn't be too hard.

These are two good starting points:

* http://devetc.org/code/2014/07/07/auto-layout-and-views-that-wrap.html
* http://stackoverflow.com/questions/12789013/ios-multi-line-uilabel-in-auto-layout

**Comment by mokagio** [comment]
@webmagnets I'm gonna close this issue, as it's not related with the library. Good luck.

**Comment by webmagnets** [comment]
I seem to be not understanding something. How would left aligned layout ever work if the cells are all the same width? 




-
Nathan Cain
501-463-6336

www.jw.org
