### ISSUE TITLE
When there are more than two groups, when the first of the second groups has only one, the head view will be shifted downward

### ISSUE THREAD

**Issue by ldy694** [mokagio/UICollectionViewLeftAlignedLayout#22]
sorry ,Is my personal reasons, resolved now，thanks.

**Comment by unrealmagicdragon** [comment]
@ldy694 Why did this happen to you? I might have the same problem, but can't find a solution. Actually for me if the first row can have 2 slots but the next can't the cell on the 3-rd row is shifted to the right.

**Comment by ldy694** [comment]
@unrealmagicdragon Because my constraint is wrong

**Comment by topLayoutGuide** [comment]
It looks like @ldy694 solved his issue, so I will close this now. Feel free to reopen it if the issue continues. 👍
