### ISSUE TITLE
cell overlap when all cell in on line and UICollectionViewScrollDirectionHorizontal

### ISSUE THREAD

**Issue by tianhao** [mokagio/UICollectionViewLeftAlignedLayout#7]
UICollectionViewLeftAlignedLayout *layout = (UICollectionViewLeftAlignedLayout *)self.collectionViewLayout;
layout.scrollDirection = UICollectionViewScrollDirectionHorizontal;

one section, some row in collectionview

**Comment by tianye2856** [comment]
Hi,
I just have the same problem!
It can not be set to UICollectionViewScrollDirectionHorizontal!
